version:  '3.9'

services:
    db:
        image: postgres:11.12-alpine
        container_name: 'symfony.db'
        restart: on-failure
        cap_add:
            - SYS_NICE
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: app_user
            POSTGRES_PASSWORD: app_pass
        volumes:
            - './bin/postgresql/:/var/lib/postgresql/data'
        ports:
            - '5432:5432'
        networks:
            - app_network

    test-db:
        image: postgres:11.12-alpine
        container_name: 'symfony.test-db'
        restart: on-failure
        cap_add:
            - SYS_NICE
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: app_user
            POSTGRES_PASSWORD: app_pass
        # volumes are not persisted in test db
        ports:
            - '8070:5432' # notice different OUT port than in default database
        networks:
            - app_network

    php:
        build:
            context: docker/php
            dockerfile: Dockerfile
            network: host
            args:
                ENV: dev # choose environment (dev/test/prod)
                TIMEZONE: Europe/Warsaw # change according to your needs
        container_name: 'symfony.php'
        expose:
            - '9000'
        restart: on-failure
        env_file:
            - docker/php/.env # ! create this file ! - choose environment (dev/test/prod) and copy correct template .dist file
        depends_on:
            - db
        volumes:
            - './app/:/var/www/app:cached'
        networks:
            - app_network

    nginx:
        build: docker/nginx
        container_name: 'symfony.nginx'
        restart: on-failure
        depends_on:
            - db
            - php
        volumes:
            - './app/:/var/www/app:cached'
            - './logs/nginx:/var/log/nginx'
        ports:
            - '8050:80'
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.24.57.0/24